services:
  # ollama:
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    # depends_on:
    #   - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3006}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://16.171.185.182:11434'
      - 'WEBUI_SECRET_KEY='
      - VIRTUAL_HOST=llm.cereinsight.com
      - CERT_NAME=cereinsight.com
      - WEBUI_NAME=Cere LLM WebUI
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    dns: 8.8.8.8

volumes:
  # ollama: {}
  open-webui: {}

networks:
  default:
    external:
      name: webproxy
